### ISSUE TITLE
Test driven development

### ISSUE THREAD

**Issue by notro** [adafruit/rosie-ci#2]
@tannewt:

I've started to look at implementing I2C slave support and I think I'm going to do a test driven development.
I'll hook a Feather M0 Express to a Raspberry Pi: usb and i2c. Then I can run tests on the Pi that exercises the linux ds1307 driver.
I have done an Arduino library that implements I2c slave support and when I did that I did all the testing manually and it's very tedious in the long run.

I should be able to run the tests from my linux build computer (not Pi), the firmware and tests should be copied over, installed and run easily.

AFAIU rosie-ci it's for running tests based on travis builds. Where does the tests come from?

Maybe it's possible to find some common ground here where we can share code and effort.

These are my needs:
- Reset board through gpio (RST pin) if necessary. Don't want to push buttons.
- Upload firmware to board
- Upload files with reload disabled, so I can decide when to start running tests
- Two types of tests: one to run on the board and one to run on the Pi
- Test results are reported back in realtime
- Access to repl over network, ser2net maybe

I had a quick look at PlatformIO which looked very promising, but it costs money to do unit testing and it seems to be mostly for paying customers: https://community.platformio.org/t/why-did-i-completely-stop-using-platformio/2600

I see that rosie-ci has it's own repl interaction code, isn't there a common library that does this stuff?
Does every developer build their own tools to work with these MP/CP boards?

**Comment by tannewt** [comment]
I'd love to have more automated testing! Much of what we do now is manual.

Rosie currently runs tests from here: https://github.com/adafruit/circuitpython/tree/master/tests/basics We don't do any tests that interact with external devices.

Sharing code would be amazing.

You can reset the board through the REPL or through baudrate=1200 connections currently. GPIO would be nice though in case those mechanics are broken.

Uploading is done by rosie already but it hasn't been refactored out yet. It'd be nice to though so we could support the ESP8266 and nRF52.

We don't have any tests that coordinate with the host. We also don't support real-time yet or repl over network. It all sounds useful though.

As I said earlier, the REPL code should be factored out but it hasn't yet. (I tend to hack things together and refactor as it gets more complicated and clearer how it can be organized.)

I think we all have basic tweaks to a manual testing process. I tend to connect my board, copy a test script over and then disconnect from usb. I then use GDB to load and reload newer test versions. I use a Saleae to monitor the funcitonality externally to know how well things are working.

This tool makes validating registers easier: https://github.com/tannewt/PyCortexMDebug

I've invited you to collaborate on CircuitPython so I can assign the I2C slave issue to you. Thanks!

**Comment by notro** [comment]
Ok thanks, I'll pull out the bits I need and come back when I have settled on something.

**Comment by tannewt** [comment]
Great! Thank you!

**Comment by notro** [comment]
I've spent some time on this and I think I'm settling on adding/using a *tools/cpboard.py*: https://gist.github.com/notro/1063505b2eb72720dfe419ea74de1b31.
I can use it to upload firmware and access the repl over ssh.
Additionally if I make *tests/pyboard.py* point to it, I can use *tests/run-tests* to run tests on the board.
I haven't look that much on the test results, but they differ depending on running them through the repl or through code.py.

Is this something you could make use of?

If I had the funds or were doing this professionally, I would have gotten myself a USB hub that can control power per port: https://github.com/mvp/uhubctl
(the Pi can't do that, hardwired power) Looks to be a really nice way of resetting the boards. During my work on this I have had several times were I could access the serial but not the USB drive. Most of the time unplug/plug would solve it, but not always.

When the board is in the bootloader, is there a way to reset it back to normal through serial?

**Comment by tannewt** [comment]
@notro `cpboard.py` looks very useful! Please PR it.

I never knew you could do individual power per port! I have a few Plugable hubs that look like they may work! They aren't what I use with Rosie yet though. I was originally just thinking about external reset line control instead of power.

I believe there is a way to reset to normal through serial because there is a serial API for use with arduino/bossac. It looks like its 'W' but I haven't tested it. The code is here: https://github.com/Microsoft/uf2-samdx1/blob/master/src/sam_ba_monitor.c#L129
